/*
 * Generated by Bluespec Compiler, version 2021.12.1-27-g9a7d5e05 (build 9a7d5e05)
 * 
 * On Wed May 25 20:01:50 IST 2022
 * 
 */

/* Generation options: */
#ifndef __mkButterfly_h__
#define __mkButterfly_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkButterfly module */
class MOD_mkButterfly : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_d;
  MOD_Reg<tUInt8> INST_rflag;
  MOD_Reg<tUInt32> INST_s;
 
 /* Constructor */
 public:
  MOD_mkButterfly(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_rflag__h239;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_butterfly(tUInt32 ARG_butterfly_x, tUInt32 ARG_butterfly_y);
  tUInt8 METH_RDY_butterfly();
  tUInt32 METH_sum();
  tUInt8 METH_RDY_sum();
  tUInt32 METH_diff();
  tUInt8 METH_RDY_diff();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkButterfly &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkButterfly &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkButterfly &backing);
};

#endif /* ifndef __mkButterfly_h__ */
