/*
 * Generated by Bluespec Compiler, version 2021.12.1-27-g9a7d5e05 (build 9a7d5e05)
 * 
 * On Wed May 25 20:01:50 IST 2022
 * 
 */

/* Generation options: */
#ifndef __mkDCT2_h__
#define __mkDCT2_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkButterfly.h"
#include "mkCosineLUT.h"


/* Class declaration for the mkDCT2 module */
class MOD_mkDCT2 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkButterfly INST_fly_0;
  MOD_mkButterfly INST_fly_1;
  MOD_mkButterfly INST_fly_2;
  MOD_mkCosineLUT INST_lut;
  MOD_Reg<tUInt8> INST_stage;
  MOD_Reg<tUInt32> INST_x_0;
  MOD_Reg<tUInt32> INST_x_1;
  MOD_Reg<tUInt32> INST_x_2;
  MOD_Reg<tUInt32> INST_x_3;
  MOD_Reg<tUInt32> INST_x_4;
  MOD_Reg<tUInt32> INST_x_5;
  MOD_Reg<tUInt32> INST_x_6;
  MOD_Reg<tUInt32> INST_x_7;
 
 /* Constructor */
 public:
  MOD_mkDCT2(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_fetch_Input_signal;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_stage_EQ_3___d43;
  tUInt8 DEF_x__h1462;
 
 /* Local definitions */
 private:
  tUInt32 DEF_b__h1450;
  tUInt32 DEF_b__h1439;
  tUInt32 DEF_b__h1341;
  tUInt32 DEF_b__h1393;
  tUInt32 DEF_b__h1383;
  tUInt32 DEF_b__h1328;
 
 /* Rules */
 public:
  void RL_fly2();
  void RL_out1();
 
 /* Methods */
 public:
  void METH_fetch_Input(tUWide ARG_fetch_Input_signal);
  tUInt8 METH_RDY_fetch_Input();
  void METH_result_0__write(tUInt32 ARG_result_0__write_1);
  tUInt8 METH_RDY_result_0__write();
  tUInt32 METH_result_0__read();
  tUInt8 METH_RDY_result_0__read();
  void METH_result_1__write(tUInt32 ARG_result_1__write_1);
  tUInt8 METH_RDY_result_1__write();
  tUInt32 METH_result_1__read();
  tUInt8 METH_RDY_result_1__read();
  void METH_result_2__write(tUInt32 ARG_result_2__write_1);
  tUInt8 METH_RDY_result_2__write();
  tUInt32 METH_result_2__read();
  tUInt8 METH_RDY_result_2__read();
  void METH_result_3__write(tUInt32 ARG_result_3__write_1);
  tUInt8 METH_RDY_result_3__write();
  tUInt32 METH_result_3__read();
  tUInt8 METH_RDY_result_3__read();
  void METH_result_4__write(tUInt32 ARG_result_4__write_1);
  tUInt8 METH_RDY_result_4__write();
  tUInt32 METH_result_4__read();
  tUInt8 METH_RDY_result_4__read();
  void METH_result_5__write(tUInt32 ARG_result_5__write_1);
  tUInt8 METH_RDY_result_5__write();
  tUInt32 METH_result_5__read();
  tUInt8 METH_RDY_result_5__read();
  void METH_result_6__write(tUInt32 ARG_result_6__write_1);
  tUInt8 METH_RDY_result_6__write();
  tUInt32 METH_result_6__read();
  tUInt8 METH_RDY_result_6__read();
  void METH_result_7__write(tUInt32 ARG_result_7__write_1);
  tUInt8 METH_RDY_result_7__write();
  tUInt32 METH_result_7__read();
  tUInt8 METH_RDY_result_7__read();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDCT2 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkDCT2 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkDCT2 &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkDCT2 &backing);
};

#endif /* ifndef __mkDCT2_h__ */
