/*
 * Generated by Bluespec Compiler, version 2021.12.1-27-g9a7d5e05 (build 9a7d5e05)
 * 
 * On Wed May 25 20:01:50 IST 2022
 * 
 */
#include "bluesim_primitives.h"
#include "mkInt2Fxp.h"


/* Constructor */
MOD_mkInt2Fxp::MOD_mkInt2Fxp(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_flag(simHdl, "flag", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_x_0(simHdl, "x_0", this, 32u, 0u, (tUInt8)0u),
    INST_x_1(simHdl, "x_1", this, 32u, 0u, (tUInt8)0u),
    INST_x_2(simHdl, "x_2", this, 32u, 0u, (tUInt8)0u),
    INST_x_3(simHdl, "x_3", this, 32u, 0u, (tUInt8)0u),
    INST_x_4(simHdl, "x_4", this, 32u, 0u, (tUInt8)0u),
    INST_x_5(simHdl, "x_5", this, 32u, 0u, (tUInt8)0u),
    INST_x_6(simHdl, "x_6", this, 32u, 0u, (tUInt8)0u),
    INST_x_7(simHdl, "x_7", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246(216u),
    DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167(144u),
    DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88(72u)
{
  PORT_fetch_Input_signal.setSize(256u);
  PORT_fetch_Input_signal.clear();
  PORT_result.setSize(288u);
  PORT_result.clear();
  symbol_count = 12u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkInt2Fxp::init_symbols_0()
{
  init_symbol(&symbols[0u], "fetch_Input_signal", SYM_PORT, &PORT_fetch_Input_signal, 256u);
  init_symbol(&symbols[1u], "flag", SYM_MODULE, &INST_flag);
  init_symbol(&symbols[2u], "flag__h614", SYM_DEF, &DEF_flag__h614, 1u);
  init_symbol(&symbols[3u], "result", SYM_PORT, &PORT_result, 288u);
  init_symbol(&symbols[4u], "x_0", SYM_MODULE, &INST_x_0);
  init_symbol(&symbols[5u], "x_1", SYM_MODULE, &INST_x_1);
  init_symbol(&symbols[6u], "x_2", SYM_MODULE, &INST_x_2);
  init_symbol(&symbols[7u], "x_3", SYM_MODULE, &INST_x_3);
  init_symbol(&symbols[8u], "x_4", SYM_MODULE, &INST_x_4);
  init_symbol(&symbols[9u], "x_5", SYM_MODULE, &INST_x_5);
  init_symbol(&symbols[10u], "x_6", SYM_MODULE, &INST_x_6);
  init_symbol(&symbols[11u], "x_7", SYM_MODULE, &INST_x_7);
}


/* Rule actions */


/* Methods */

void MOD_mkInt2Fxp::METH_fetch_Input(tUWide ARG_fetch_Input_signal)
{
  tUInt32 DEF_b__h920;
  tUInt32 DEF_b__h1199;
  tUInt32 DEF_b__h1292;
  tUInt32 DEF_b__h1385;
  tUInt32 DEF_b__h1478;
  tUInt32 DEF_b__h1571;
  tUInt32 DEF_b__h1664;
  tUInt32 DEF_b__h1757;
  PORT_fetch_Input_signal = ARG_fetch_Input_signal;
  DEF_b__h1757 = ARG_fetch_Input_signal.get_whole_word(7u);
  DEF_b__h1664 = ARG_fetch_Input_signal.get_whole_word(6u);
  DEF_b__h1571 = ARG_fetch_Input_signal.get_whole_word(5u);
  DEF_b__h1478 = ARG_fetch_Input_signal.get_whole_word(4u);
  DEF_b__h1385 = ARG_fetch_Input_signal.get_whole_word(3u);
  DEF_b__h1292 = ARG_fetch_Input_signal.get_whole_word(2u);
  DEF_b__h1199 = ARG_fetch_Input_signal.get_whole_word(1u);
  DEF_b__h920 = ARG_fetch_Input_signal.get_whole_word(0u);
  INST_x_0.METH_write(DEF_b__h920);
  INST_x_1.METH_write(DEF_b__h1199);
  INST_x_2.METH_write(DEF_b__h1292);
  INST_x_3.METH_write(DEF_b__h1385);
  INST_x_4.METH_write(DEF_b__h1478);
  INST_x_5.METH_write(DEF_b__h1571);
  INST_x_6.METH_write(DEF_b__h1664);
  INST_x_7.METH_write(DEF_b__h1757);
  INST_flag.METH_write((tUInt8)1u);
}

tUInt8 MOD_mkInt2Fxp::METH_RDY_fetch_Input()
{
  tUInt8 DEF_CAN_FIRE_fetch_Input;
  tUInt8 PORT_RDY_fetch_Input;
  DEF_flag__h614 = INST_flag.METH_read();
  DEF_CAN_FIRE_fetch_Input = !DEF_flag__h614;
  PORT_RDY_fetch_Input = DEF_CAN_FIRE_fetch_Input;
  return PORT_RDY_fetch_Input;
}

tUWide MOD_mkInt2Fxp::METH_result()
{
  tUInt8 DEF_y_f__h4406;
  tUInt8 DEF_y_f__h7396;
  tUInt8 DEF_y_f__h10386;
  tUInt8 DEF_y_f__h13376;
  tUInt8 DEF_y_f__h16366;
  tUInt8 DEF_y_f__h19356;
  tUInt8 DEF_y_f__h22346;
  tUInt8 DEF_y_f__h25336;
  tUInt64 DEF_IF_NOT_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_ETC___d285;
  tUInt64 DEF_IF_NOT_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_ETC___d324;
  tUInt64 DEF_x__h3648;
  tUInt64 DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_SEXT_x_7_0_1_ETC___d16;
  tUInt64 DEF_x__h6641;
  tUInt64 DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_SEXT_x_6_9_0_ETC___d55;
  tUInt64 DEF_x__h9631;
  tUInt64 DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_SEXT_x_5_9_0_ETC___d95;
  tUInt64 DEF_x__h12621;
  tUInt64 DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_SEXT_x_4__ETC___d134;
  tUInt64 DEF_x__h15611;
  tUInt64 DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_SEXT_x_3__ETC___d174;
  tUInt64 DEF_x__h18601;
  tUInt64 DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_SEXT_x_2__ETC___d213;
  tUInt64 DEF_x__h21591;
  tUInt64 DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_SEXT_x_1__ETC___d253;
  tUInt64 DEF_x__h24581;
  tUInt64 DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_SEXT_x_0__ETC___d292;
  tUInt64 DEF_ax2_i__h3567;
  tUInt8 DEF_ax2_i_BIT_32___h3620;
  tUInt64 DEF_ax2_i__h6560;
  tUInt8 DEF_ax2_i_BIT_32___h6613;
  tUInt64 DEF_ax2_i__h9550;
  tUInt8 DEF_ax2_i_BIT_32___h9603;
  tUInt64 DEF_ax2_i__h12540;
  tUInt8 DEF_ax2_i_BIT_32___h12593;
  tUInt64 DEF_ax2_i__h15530;
  tUInt8 DEF_ax2_i_BIT_32___h15583;
  tUInt64 DEF_ax2_i__h18520;
  tUInt8 DEF_ax2_i_BIT_32___h18573;
  tUInt64 DEF_ax2_i__h21510;
  tUInt8 DEF_ax2_i_BIT_32___h21563;
  tUInt64 DEF_ax2_i__h24500;
  tUInt8 DEF_ax2_i_BIT_32___h24553;
  tUInt64 DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d28;
  tUInt8 DEF_x_BIT_35___h5701;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d32;
  tUInt64 DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d67;
  tUInt8 DEF_x_BIT_35___h8691;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d71;
  tUInt64 DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d107;
  tUInt8 DEF_x_BIT_35___h11681;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d111;
  tUInt64 DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d146;
  tUInt8 DEF_x_BIT_35___h14671;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d150;
  tUInt64 DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d186;
  tUInt8 DEF_x_BIT_35___h17661;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d190;
  tUInt64 DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d225;
  tUInt8 DEF_x_BIT_35___h20651;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d229;
  tUInt64 DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d265;
  tUInt8 DEF_x_BIT_35___h23641;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d269;
  tUInt64 DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d304;
  tUInt8 DEF_x_BIT_35___h26631;
  tUInt8 DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d308;
  tUInt8 DEF_x_BIT_0___h4390;
  tUInt8 DEF_x_BIT_1___h4038;
  tUInt8 DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d19;
  tUInt8 DEF_x_BIT_0___h7380;
  tUInt8 DEF_x_BIT_1___h7028;
  tUInt8 DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d58;
  tUInt8 DEF_x_BIT_0___h10370;
  tUInt8 DEF_x_BIT_1___h10018;
  tUInt8 DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d98;
  tUInt8 DEF_x_BIT_0___h13360;
  tUInt8 DEF_x_BIT_1___h13008;
  tUInt8 DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d137;
  tUInt8 DEF_x_BIT_0___h16350;
  tUInt8 DEF_x_BIT_1___h15998;
  tUInt8 DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d177;
  tUInt8 DEF_x_BIT_0___h19340;
  tUInt8 DEF_x_BIT_1___h18988;
  tUInt8 DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d216;
  tUInt8 DEF_x_BIT_0___h22330;
  tUInt8 DEF_x_BIT_1___h21978;
  tUInt8 DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d256;
  tUInt8 DEF_x_BIT_0___h25320;
  tUInt8 DEF_x_BIT_1___h24968;
  tUInt8 DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d295;
  tUInt8 DEF_check__h2825;
  tUInt8 DEF_check__h5838;
  tUInt8 DEF_check__h8828;
  tUInt8 DEF_check__h11818;
  tUInt8 DEF_check__h14808;
  tUInt8 DEF_check__h17798;
  tUInt8 DEF_check__h20788;
  tUInt8 DEF_check__h23778;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d31;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d70;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d110;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d149;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d189;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d228;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d268;
  tUInt64 DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d307;
  tUInt64 DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d18;
  tUInt64 DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d57;
  tUInt64 DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d97;
  tUInt64 DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d136;
  tUInt64 DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d176;
  tUInt64 DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d215;
  tUInt64 DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d255;
  tUInt64 DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d294;
  tUInt32 DEF_x__h24508;
  tUInt32 DEF_x__h21518;
  tUInt32 DEF_x__h18528;
  tUInt32 DEF_x__h15538;
  tUInt32 DEF_x__h12548;
  tUInt32 DEF_x__h9558;
  tUInt32 DEF_x__h6568;
  tUInt32 DEF_x__h3575;
  DEF_x__h3575 = INST_x_7.METH_read();
  DEF_x__h6568 = INST_x_6.METH_read();
  DEF_x__h9558 = INST_x_5.METH_read();
  DEF_x__h12548 = INST_x_4.METH_read();
  DEF_x__h18528 = INST_x_2.METH_read();
  DEF_x__h15538 = INST_x_3.METH_read();
  DEF_x__h21518 = INST_x_1.METH_read();
  DEF_x__h24508 = INST_x_0.METH_read();
  DEF_ax2_i__h24500 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h24508));
  DEF_ax2_i_BIT_32___h24553 = (tUInt8)(DEF_ax2_i__h24500 >> 32u);
  DEF_ax2_i__h21510 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h21518));
  DEF_ax2_i_BIT_32___h21563 = (tUInt8)(DEF_ax2_i__h21510 >> 32u);
  DEF_ax2_i__h18520 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h18528));
  DEF_ax2_i_BIT_32___h18573 = (tUInt8)(DEF_ax2_i__h18520 >> 32u);
  DEF_ax2_i__h15530 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h15538));
  DEF_ax2_i_BIT_32___h15583 = (tUInt8)(DEF_ax2_i__h15530 >> 32u);
  DEF_ax2_i__h12540 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h12548));
  DEF_ax2_i_BIT_32___h12593 = (tUInt8)(DEF_ax2_i__h12540 >> 32u);
  DEF_ax2_i__h9550 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h9558));
  DEF_ax2_i_BIT_32___h9603 = (tUInt8)(DEF_ax2_i__h9550 >> 32u);
  DEF_ax2_i__h6560 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h6568));
  DEF_ax2_i_BIT_32___h6613 = (tUInt8)(DEF_ax2_i__h6560 >> 32u);
  DEF_ax2_i__h3567 = primSignExt64(33u, 32u, (tUInt32)(DEF_x__h3575));
  DEF_ax2_i_BIT_32___h3620 = (tUInt8)(DEF_ax2_i__h3567 >> 32u);
  DEF_x__h24581 = 8796093022207llu & ((DEF_ax2_i__h24500 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_SEXT_x_0__ETC___d292 = primShiftR64(43u,
									       43u,
									       (tUInt64)(DEF_ax2_i_BIT_32___h24553 ? 8796093022207llu & -DEF_x__h24581 : DEF_x__h24581),
									       32u,
									       13u);
  DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d294 = DEF_ax2_i_BIT_32___h24553 ? 8796093022207llu & -DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_SEXT_x_0__ETC___d292 : DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_SEXT_x_0__ETC___d292;
  DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d295 = (tUInt8)(DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d294 >> 42u);
  DEF_x_BIT_1___h24968 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d294 >> 1u));
  DEF_x_BIT_0___h25320 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d294);
  DEF_x__h21591 = 8796093022207llu & ((DEF_ax2_i__h21510 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_SEXT_x_1__ETC___d253 = primShiftR64(43u,
									       43u,
									       (tUInt64)(DEF_ax2_i_BIT_32___h21563 ? 8796093022207llu & -DEF_x__h21591 : DEF_x__h21591),
									       32u,
									       21u);
  DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d255 = DEF_ax2_i_BIT_32___h21563 ? 8796093022207llu & -DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_SEXT_x_1__ETC___d253 : DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_SEXT_x_1__ETC___d253;
  DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d256 = (tUInt8)(DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d255 >> 42u);
  DEF_x_BIT_1___h21978 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d255 >> 1u));
  DEF_x_BIT_0___h22330 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d255);
  DEF_x__h18601 = 8796093022207llu & ((DEF_ax2_i__h18520 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_SEXT_x_2__ETC___d213 = primShiftR64(43u,
									       43u,
									       (tUInt64)(DEF_ax2_i_BIT_32___h18573 ? 8796093022207llu & -DEF_x__h18601 : DEF_x__h18601),
									       32u,
									       13u);
  DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d215 = DEF_ax2_i_BIT_32___h18573 ? 8796093022207llu & -DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_SEXT_x_2__ETC___d213 : DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_SEXT_x_2__ETC___d213;
  DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d216 = (tUInt8)(DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d215 >> 42u);
  DEF_x_BIT_1___h18988 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d215 >> 1u));
  DEF_x_BIT_0___h19340 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d215);
  DEF_x__h15611 = 8796093022207llu & ((DEF_ax2_i__h15530 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_SEXT_x_3__ETC___d174 = primShiftR64(43u,
									       43u,
									       (tUInt64)(DEF_ax2_i_BIT_32___h15583 ? 8796093022207llu & -DEF_x__h15611 : DEF_x__h15611),
									       32u,
									       21u);
  DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d176 = DEF_ax2_i_BIT_32___h15583 ? 8796093022207llu & -DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_SEXT_x_3__ETC___d174 : DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_SEXT_x_3__ETC___d174;
  DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d177 = (tUInt8)(DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d176 >> 42u);
  DEF_x_BIT_1___h15998 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d176 >> 1u));
  DEF_x_BIT_0___h16350 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d176);
  DEF_x__h12621 = 8796093022207llu & ((DEF_ax2_i__h12540 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_SEXT_x_4__ETC___d134 = primShiftR64(43u,
									       43u,
									       (tUInt64)(DEF_ax2_i_BIT_32___h12593 ? 8796093022207llu & -DEF_x__h12621 : DEF_x__h12621),
									       32u,
									       13u);
  DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d136 = DEF_ax2_i_BIT_32___h12593 ? 8796093022207llu & -DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_SEXT_x_4__ETC___d134 : DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_SEXT_x_4__ETC___d134;
  DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d137 = (tUInt8)(DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d136 >> 42u);
  DEF_x_BIT_1___h13008 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d136 >> 1u));
  DEF_x_BIT_0___h13360 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d136);
  DEF_x__h9631 = 8796093022207llu & ((DEF_ax2_i__h9550 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_SEXT_x_5_9_0_ETC___d95 = primShiftR64(43u,
									      43u,
									      (tUInt64)(DEF_ax2_i_BIT_32___h9603 ? 8796093022207llu & -DEF_x__h9631 : DEF_x__h9631),
									      32u,
									      21u);
  DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d97 = DEF_ax2_i_BIT_32___h9603 ? 8796093022207llu & -DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_SEXT_x_5_9_0_ETC___d95 : DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_SEXT_x_5_9_0_ETC___d95;
  DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d98 = (tUInt8)(DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d97 >> 42u);
  DEF_x_BIT_1___h10018 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d97 >> 1u));
  DEF_x_BIT_0___h10370 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d97);
  DEF_x__h6641 = 8796093022207llu & ((DEF_ax2_i__h6560 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_SEXT_x_6_9_0_ETC___d55 = primShiftR64(43u,
									      43u,
									      (tUInt64)(DEF_ax2_i_BIT_32___h6613 ? 8796093022207llu & -DEF_x__h6641 : DEF_x__h6641),
									      32u,
									      13u);
  DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d57 = DEF_ax2_i_BIT_32___h6613 ? 8796093022207llu & -DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_SEXT_x_6_9_0_ETC___d55 : DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_SEXT_x_6_9_0_ETC___d55;
  DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d58 = (tUInt8)(DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d57 >> 42u);
  DEF_x_BIT_1___h7028 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d57 >> 1u));
  DEF_x_BIT_0___h7380 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d57);
  DEF_x__h3648 = 8796093022207llu & ((DEF_ax2_i__h3567 << 10u) | (tUInt64)(0u));
  DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_SEXT_x_7_0_1_ETC___d16 = primShiftR64(43u,
									      43u,
									      (tUInt64)(DEF_ax2_i_BIT_32___h3620 ? 8796093022207llu & -DEF_x__h3648 : DEF_x__h3648),
									      32u,
									      21u);
  DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d18 = DEF_ax2_i_BIT_32___h3620 ? 8796093022207llu & -DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_SEXT_x_7_0_1_ETC___d16 : DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_SEXT_x_7_0_1_ETC___d16;
  DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d19 = (tUInt8)(DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d18 >> 42u);
  DEF_x_BIT_1___h4038 = (tUInt8)((tUInt8)1u & (DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d18 >> 1u));
  DEF_x_BIT_0___h4390 = (tUInt8)((tUInt8)1u & DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d18);
  DEF_y_f__h25336 = DEF_x_BIT_1___h24968 && (DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d295 || DEF_x_BIT_0___h25320) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d304 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d294 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h25336))));
  DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d307 = !DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d295 && (tUInt8)(DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d304 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_SEXT_x_ETC___d304;
  DEF_check__h23778 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d307 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d308 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d307 >> 40u);
  DEF_x_BIT_35___h26631 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d307 >> 35u));
  DEF_IF_NOT_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_ETC___d324 = !DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d308 && (DEF_x_BIT_35___h26631 || !(DEF_check__h23778 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d308 && (!DEF_x_BIT_35___h26631 || !(((tUInt8)31u & ~DEF_check__h23778) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_NEG_IF_ETC___d307));
  DEF_y_f__h19356 = DEF_x_BIT_1___h18988 && (DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d216 || DEF_x_BIT_0___h19340) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d225 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d215 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h19356))));
  DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d228 = !DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d216 && (tUInt8)(DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d225 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_SEXT_x_ETC___d225;
  DEF_check__h17798 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d228 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d229 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d228 >> 40u);
  DEF_x_BIT_35___h20651 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d228 >> 35u));
  DEF_y_f__h22346 = DEF_x_BIT_1___h21978 && (DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d256 || DEF_x_BIT_0___h22330) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d265 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d255 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h22346))));
  DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d268 = !DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d256 && (tUInt8)(DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d265 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_SEXT_x_ETC___d265;
  DEF_check__h20788 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d268 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d269 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d268 >> 40u);
  DEF_x_BIT_35___h23641 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d268 >> 35u));
  DEF_IF_NOT_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_ETC___d285 = !DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d269 && (DEF_x_BIT_35___h23641 || !(DEF_check__h20788 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d269 && (!DEF_x_BIT_35___h23641 || !(((tUInt8)31u & ~DEF_check__h20788) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_NEG_IF_ETC___d268));
  DEF_y_f__h16366 = DEF_x_BIT_1___h15998 && (DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d177 || DEF_x_BIT_0___h16350) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d186 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d176 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h16366))));
  DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d189 = !DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d177 && (tUInt8)(DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d186 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_SEXT_x_ETC___d186;
  DEF_check__h14808 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d189 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d190 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d189 >> 40u);
  DEF_x_BIT_35___h17661 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d189 >> 35u));
  DEF_y_f__h13376 = DEF_x_BIT_1___h13008 && (DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d137 || DEF_x_BIT_0___h13360) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d146 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d136 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h13376))));
  DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d149 = !DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d137 && (tUInt8)(DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d146 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_SEXT_x_ETC___d146;
  DEF_check__h11818 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d149 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d150 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d149 >> 40u);
  DEF_x_BIT_35___h14671 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d149 >> 35u));
  DEF_y_f__h10386 = DEF_x_BIT_1___h10018 && (DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d98 || DEF_x_BIT_0___h10370) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d107 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d97 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h10386))));
  DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d110 = !DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d98 && (tUInt8)(DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d107 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_5__ETC___d107;
  DEF_check__h8828 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d110 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d111 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d110 >> 40u);
  DEF_x_BIT_35___h11681 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d110 >> 35u));
  DEF_y_f__h7396 = DEF_x_BIT_1___h7028 && (DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d58 || DEF_x_BIT_0___h7380) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d67 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d57 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h7396))));
  DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d70 = !DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d58 && (tUInt8)(DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d67 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SEXT_x_6__ETC___d67;
  DEF_check__h5838 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d70 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d71 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d70 >> 40u);
  DEF_x_BIT_35___h8691 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d70 >> 35u));
  DEF_y_f__h4406 = DEF_x_BIT_1___h4038 && (DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d19 || DEF_x_BIT_0___h4390) ? (tUInt8)1u : (tUInt8)0u;
  DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d28 = 2199023255551llu & (((tUInt64)(DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d18 >> 2u)) + (2199023255551llu & ((tUInt64)(DEF_y_f__h4406))));
  DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d31 = !DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d19 && (tUInt8)(DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d28 >> 40u) ? 1099511627775llu : DEF_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SEXT_x_7__ETC___d28;
  DEF_check__h2825 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d31 >> 36u);
  DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d32 = (tUInt8)(DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d31 >> 40u);
  DEF_x_BIT_35___h5701 = (tUInt8)((tUInt8)1u & (DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d31 >> 35u));
  DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88.set_bits_in_word((tUInt8)((!DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d32 && (DEF_x_BIT_35___h5701 || !(DEF_check__h2825 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d32 && (!DEF_x_BIT_35___h5701 || !(((tUInt8)31u & ~DEF_check__h2825) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d31))) >> 28u),
										2u,
										0u,
										8u).set_whole_word((((tUInt32)(268435455u & (!DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d32 && (DEF_x_BIT_35___h5701 || !(DEF_check__h2825 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d32 && (!DEF_x_BIT_35___h5701 || !(((tUInt8)31u & ~DEF_check__h2825) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NEG_IF_SE_ETC___d31))))) << 4u) | (tUInt32)((tUInt8)((!DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d71 && (DEF_x_BIT_35___h8691 || !(DEF_check__h5838 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d71 && (!DEF_x_BIT_35___h8691 || !(((tUInt8)31u & ~DEF_check__h5838) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d70))) >> 32u)),
												   1u).set_whole_word((tUInt32)(!DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d71 && (DEF_x_BIT_35___h8691 || !(DEF_check__h5838 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d71 && (!DEF_x_BIT_35___h8691 || !(((tUInt8)31u & ~DEF_check__h5838) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_6_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d70))),
														      0u);
  DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167.set_bits_in_word(primExtract32(16u,
											       72u,
											       DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88,
											       32u,
											       71u,
											       32u,
											       56u),
										 4u,
										 0u,
										 16u).set_whole_word(primExtract32(32u,
														   72u,
														   DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88,
														   32u,
														   55u,
														   32u,
														   24u),
												     3u).set_whole_word((DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88.get_bits_in_word32(0u,
																									 0u,
																									 24u) << 8u) | (tUInt32)((tUInt8)((!DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d111 && (DEF_x_BIT_35___h11681 || !(DEF_check__h8828 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d111 && (!DEF_x_BIT_35___h11681 || !(((tUInt8)31u & ~DEF_check__h8828) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d110))) >> 28u)),
															2u).set_whole_word((((tUInt32)(268435455u & (!DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d111 && (DEF_x_BIT_35___h11681 || !(DEF_check__h8828 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d111 && (!DEF_x_BIT_35___h11681 || !(((tUInt8)31u & ~DEF_check__h8828) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_5_9_0_BIT_32_1_THEN_NEG_IF_SE_ETC___d110))))) << 4u) | (tUInt32)((tUInt8)((!DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d150 && (DEF_x_BIT_35___h14671 || !(DEF_check__h11818 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d150 && (!DEF_x_BIT_35___h14671 || !(((tUInt8)31u & ~DEF_check__h11818) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d149))) >> 32u)),
																	   1u).set_whole_word((tUInt32)(!DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d150 && (DEF_x_BIT_35___h14671 || !(DEF_check__h11818 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d150 && (!DEF_x_BIT_35___h14671 || !(((tUInt8)31u & ~DEF_check__h11818) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_4_28_29_BIT_32_30_THEN_NEG_IF_ETC___d149))),
																			      0u);
  DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246.set_bits_in_word(primExtract32(24u,
											       144u,
											       DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167,
											       32u,
											       143u,
											       32u,
											       120u),
										 6u,
										 0u,
										 24u).set_whole_word(primExtract32(32u,
														   144u,
														   DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167,
														   32u,
														   119u,
														   32u,
														   88u),
												     5u).set_whole_word(primExtract32(32u,
																      144u,
																      DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167,
																      32u,
																      87u,
																      32u,
																      56u),
															4u).set_whole_word(primExtract32(32u,
																			 144u,
																			 DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167,
																			 32u,
																			 55u,
																			 32u,
																			 24u),
																	   3u).set_whole_word((DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167.get_bits_in_word32(0u,
																														0u,
																														24u) << 8u) | (tUInt32)((tUInt8)((!DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d190 && (DEF_x_BIT_35___h17661 || !(DEF_check__h14808 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d190 && (!DEF_x_BIT_35___h17661 || !(((tUInt8)31u & ~DEF_check__h14808) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d189))) >> 28u)),
																			      2u).set_whole_word((((tUInt32)(268435455u & (!DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d190 && (DEF_x_BIT_35___h17661 || !(DEF_check__h14808 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d190 && (!DEF_x_BIT_35___h17661 || !(((tUInt8)31u & ~DEF_check__h14808) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_3_68_69_BIT_32_70_THEN_NEG_IF_ETC___d189))))) << 4u) | (tUInt32)((tUInt8)((!DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d229 && (DEF_x_BIT_35___h20651 || !(DEF_check__h17798 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d229 && (!DEF_x_BIT_35___h20651 || !(((tUInt8)31u & ~DEF_check__h17798) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d228))) >> 32u)),
																						 1u).set_whole_word((tUInt32)(!DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d229 && (DEF_x_BIT_35___h20651 || !(DEF_check__h17798 == (tUInt8)0u)) ? 34359738367llu : (DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d229 && (!DEF_x_BIT_35___h20651 || !(((tUInt8)31u & ~DEF_check__h17798) == (tUInt8)0u)) ? 34359738368llu : (tUInt64)(68719476735llu & DEF_IF_NOT_IF_SEXT_x_2_07_08_BIT_32_09_THEN_NEG_IF_ETC___d228))),
																								    0u);
  PORT_result.set_whole_word(primExtract32(32u,
					   216u,
					   DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246,
					   32u,
					   215u,
					   32u,
					   184u),
			     8u).set_whole_word(primExtract32(32u,
							      216u,
							      DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246,
							      32u,
							      183u,
							      32u,
							      152u),
						7u).set_whole_word(primExtract32(32u,
										 216u,
										 DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246,
										 32u,
										 151u,
										 32u,
										 120u),
								   6u).set_whole_word(primExtract32(32u,
												    216u,
												    DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246,
												    32u,
												    119u,
												    32u,
												    88u),
										      5u).set_whole_word(primExtract32(32u,
														       216u,
														       DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246,
														       32u,
														       87u,
														       32u,
														       56u),
													 4u).set_whole_word(primExtract32(32u,
																	  216u,
																	  DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246,
																	  32u,
																	  55u,
																	  32u,
																	  24u),
															    3u).set_whole_word((DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246.get_bits_in_word32(0u,
																												 0u,
																												 24u) << 8u) | (tUInt32)((tUInt8)(DEF_IF_NOT_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_ETC___d285 >> 28u)),
																	       2u).set_whole_word((((tUInt32)(268435455u & DEF_IF_NOT_IF_NOT_IF_SEXT_x_1_47_48_BIT_32_49_THEN_ETC___d285)) << 4u) | (tUInt32)((tUInt8)(DEF_IF_NOT_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_ETC___d324 >> 32u)),
																				  1u).set_whole_word((tUInt32)(DEF_IF_NOT_IF_NOT_IF_SEXT_x_0_86_87_BIT_32_88_THEN_ETC___d324),
																						     0u);
  return PORT_result;
}

tUInt8 MOD_mkInt2Fxp::METH_RDY_result()
{
  tUInt8 DEF_CAN_FIRE_result;
  tUInt8 PORT_RDY_result;
  DEF_flag__h614 = INST_flag.METH_read();
  DEF_CAN_FIRE_result = DEF_flag__h614;
  PORT_RDY_result = DEF_CAN_FIRE_result;
  return PORT_RDY_result;
}


/* Reset routines */

void MOD_mkInt2Fxp::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_x_7.reset_RST(ARG_rst_in);
  INST_x_6.reset_RST(ARG_rst_in);
  INST_x_5.reset_RST(ARG_rst_in);
  INST_x_4.reset_RST(ARG_rst_in);
  INST_x_3.reset_RST(ARG_rst_in);
  INST_x_2.reset_RST(ARG_rst_in);
  INST_x_1.reset_RST(ARG_rst_in);
  INST_x_0.reset_RST(ARG_rst_in);
  INST_flag.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkInt2Fxp::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkInt2Fxp::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_flag.dump_state(indent + 2u);
  INST_x_0.dump_state(indent + 2u);
  INST_x_1.dump_state(indent + 2u);
  INST_x_2.dump_state(indent + 2u);
  INST_x_3.dump_state(indent + 2u);
  INST_x_4.dump_state(indent + 2u);
  INST_x_5.dump_state(indent + 2u);
  INST_x_6.dump_state(indent + 2u);
  INST_x_7.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkInt2Fxp::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 16u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167", 144u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246", 216u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88", 72u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "flag__h614", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fetch_Input_signal", 256u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "result", 288u);
  num = INST_flag.dump_VCD_defs(num);
  num = INST_x_0.dump_VCD_defs(num);
  num = INST_x_1.dump_VCD_defs(num);
  num = INST_x_2.dump_VCD_defs(num);
  num = INST_x_3.dump_VCD_defs(num);
  num = INST_x_4.dump_VCD_defs(num);
  num = INST_x_5.dump_VCD_defs(num);
  num = INST_x_6.dump_VCD_defs(num);
  num = INST_x_7.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkInt2Fxp::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkInt2Fxp &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkInt2Fxp::vcd_defs(tVCDDumpType dt, MOD_mkInt2Fxp &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 144u);
    vcd_write_x(sim_hdl, num++, 216u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 256u);
    vcd_write_x(sim_hdl, num++, 288u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167) != DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167, 144u);
	backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167 = DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167;
      }
      ++num;
      if ((backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246) != DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246, 216u);
	backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246 = DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246;
      }
      ++num;
      if ((backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88) != DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88, 72u);
	backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88 = DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_flag__h614) != DEF_flag__h614)
      {
	vcd_write_val(sim_hdl, num, DEF_flag__h614, 1u);
	backing.DEF_flag__h614 = DEF_flag__h614;
      }
      ++num;
      if ((backing.PORT_fetch_Input_signal) != PORT_fetch_Input_signal)
      {
	vcd_write_val(sim_hdl, num, PORT_fetch_Input_signal, 256u);
	backing.PORT_fetch_Input_signal = PORT_fetch_Input_signal;
      }
      ++num;
      if ((backing.PORT_result) != PORT_result)
      {
	vcd_write_val(sim_hdl, num, PORT_result, 288u);
	backing.PORT_result = PORT_result;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167, 144u);
      backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167 = DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d167;
      vcd_write_val(sim_hdl, num++, DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246, 216u);
      backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246 = DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d246;
      vcd_write_val(sim_hdl, num++, DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88, 72u);
      backing.DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88 = DEF_IF_NOT_IF_NOT_IF_SEXT_x_7_0_1_BIT_32_2_THEN_NE_ETC___d88;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_flag__h614, 1u);
      backing.DEF_flag__h614 = DEF_flag__h614;
      vcd_write_val(sim_hdl, num++, PORT_fetch_Input_signal, 256u);
      backing.PORT_fetch_Input_signal = PORT_fetch_Input_signal;
      vcd_write_val(sim_hdl, num++, PORT_result, 288u);
      backing.PORT_result = PORT_result;
    }
}

void MOD_mkInt2Fxp::vcd_prims(tVCDDumpType dt, MOD_mkInt2Fxp &backing)
{
  INST_flag.dump_VCD(dt, backing.INST_flag);
  INST_x_0.dump_VCD(dt, backing.INST_x_0);
  INST_x_1.dump_VCD(dt, backing.INST_x_1);
  INST_x_2.dump_VCD(dt, backing.INST_x_2);
  INST_x_3.dump_VCD(dt, backing.INST_x_3);
  INST_x_4.dump_VCD(dt, backing.INST_x_4);
  INST_x_5.dump_VCD(dt, backing.INST_x_5);
  INST_x_6.dump_VCD(dt, backing.INST_x_6);
  INST_x_7.dump_VCD(dt, backing.INST_x_7);
}
