/*
 * Generated by Bluespec Compiler, version 2021.12.1-27-g9a7d5e05 (build 9a7d5e05)
 * 
 * On Wed May 25 20:01:50 IST 2022
 * 
 */

/* Generation options: */
#ifndef __mkTop_h__
#define __mkTop_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkDCT1.h"
#include "mkDCT2.h"
#include "mkDCT3.h"
#include "mkDCT4.h"
#include "mkInt2Fxp.h"


/* Class declaration for the mkTop module */
class MOD_mkTop : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkDCT1 INST_dct1;
  MOD_mkDCT2 INST_dct2;
  MOD_mkDCT3 INST_dct3;
  MOD_mkDCT4 INST_dct4;
  MOD_Reg<tUInt32> INST_f_0;
  MOD_Reg<tUInt32> INST_f_1;
  MOD_Reg<tUInt32> INST_f_2;
  MOD_Reg<tUInt32> INST_f_3;
  MOD_Reg<tUInt32> INST_f_4;
  MOD_Reg<tUInt32> INST_f_5;
  MOD_Reg<tUInt32> INST_f_6;
  MOD_Reg<tUInt32> INST_f_7;
  MOD_Reg<tUInt8> INST_flag;
  MOD_mkInt2Fxp INST_int2fxp;
 
 /* Constructor */
 public:
  MOD_mkTop(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_int2fxp_result____d132;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d512;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d503;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d494;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d464;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d455;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d446;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d416;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d407;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d398;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d368;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d359;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d350;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d320;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d311;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d302;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d272;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d263;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d254;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d224;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d215;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d206;
  tUWide DEF__10_MUL_10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_ETC___d176;
  tUWide DEF__10_MUL_10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fx_ETC___d167;
  tUWide DEF__10_MUL_0_CONCAT_0_CONCAT_IF_SEXT_int2fxp_resul_ETC___d158;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_287_T_ETC___d508;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_287_T_ETC___d499;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_287_T_ETC___d491;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_251_T_ETC___d460;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_251_T_ETC___d451;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_251_T_ETC___d443;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_215_T_ETC___d412;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_215_T_ETC___d403;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_215_T_ETC___d395;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_179_T_ETC___d364;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_179_T_ETC___d355;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_179_T_ETC___d347;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_143_T_ETC___d316;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_143_T_ETC___d307;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_143_T_ETC___d299;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_107_T_ETC___d268;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_107_T_ETC___d259;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_107_T_ETC___d251;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_71_TO_ETC___d220;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_71_TO_ETC___d211;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_71_TO_ETC___d203;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_35_TO_ETC___d172;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_35_TO_ETC___d163;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_35_TO_ETC___d155;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_287_T_ETC___d488;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_251_T_ETC___d440;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_215_T_ETC___d392;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_179_T_ETC___d344;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_143_T_ETC___d296;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_107_T_ETC___d248;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_71_TO_ETC___d200;
  tUWide DEF__0_CONCAT_IF_SEXT_int2fxp_result__32_BITS_35_TO_ETC___d152;
  tUWide DEF_dct4_result_7__read__17_CONCAT_dct4_result_6___ETC___d128;
  tUWide DEF_dct4_result_7__read__17_CONCAT_dct4_result_6___ETC___d125;
  tUWide DEF_dct3_result_7__read__6_CONCAT_dct3_result_6__r_ETC___d97;
  tUWide DEF_dct3_result_7__read__6_CONCAT_dct3_result_6__r_ETC___d94;
  tUWide DEF_dct1_result_7__read__4_CONCAT_dct1_result_6__r_ETC___d35;
  tUWide DEF_dct1_result_7__read__4_CONCAT_dct1_result_6__r_ETC___d32;
  tUWide DEF_dct2_result_7__read__5_CONCAT_dct2_result_6__r_ETC___d66;
  tUWide DEF_dct2_result_7__read__5_CONCAT_dct2_result_6__r_ETC___d63;
  tUWide DEF_dct4_result_7__read__17_CONCAT_dct4_result_6___ETC___d122;
  tUWide DEF_dct3_result_7__read__6_CONCAT_dct3_result_6__r_ETC___d91;
  tUWide DEF_dct1_result_7__read__4_CONCAT_dct1_result_6__r_ETC___d29;
  tUWide DEF_dct2_result_7__read__5_CONCAT_dct2_result_6__r_ETC___d60;
 
 /* Rules */
 public:
  void RL_stage1();
  void RL_stage2();
  void RL_stage3();
  void RL_stage4();
  void RL_transform();
  void RL_result();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTop &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTop &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTop &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTop &backing);
};

#endif /* ifndef __mkTop_h__ */
